spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/database_relationships_springboot
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true